[package]
name = "enegine"
version = "0.1.0"
authors = ["brsnb <49287229+brsnb@users.noreply.github.com>"]
edition = "2018"


[dependencies]
ash = "0.31"
ash-window = "0.4"
env_logger = "0.7"
log = "0.4"
shaderc = "0.6"
winit = "0.22"
